"""General algorithm parameters"""
RECOMBINARION_PROB = 0.5
MUTATION_PROB = 0.05
POPULATION_SIZE = 8
PRECISION = 2
EXTREMUM = "max" #can be min or max
NUMBER_OF_PAIRS = 10
NUMBER_OF_ITERATIONS = 5
SELECTION_METHOD = "elitistic"