"""General algorithm parameters"""
RECOMBINARION_PROB = 0.25
MUTATION_PROB = 0.05
POPULATION_SIZE = 4
PRECISION = 2
EXTREMUM = "max" #can be min or max
NUMBER_OF_PAIRS = 2
NUMBER_OF_ITERATIONS = 3
SELECTION_METHOD = "roulette"
